field_mapping = {
    # === Company Information ===
    "companyname_c": "company_name",
    "cin_c": "cin",
    "gln_c": "gln",
    "companyadd_c": "registered_office",
    "emailid_c": "company_email",
    # === Auditor Information ===
    "nameauditorfirm_c": "auditor_name",
    "pan_c": "auditor_pan",
    "membershnum": "auditor_frn_or_membership",
    "permaddress2a_c": "auditor_address_line1",
    "permaddress2b_c": "auditor_address_line2",
    "city_c": "auditor_city",
    "state_p": "auditor_state",
    "pin_c": "auditor_pin",
    "country_c": "auditor_country",
    "email": "auditor_email",
    "categoryofauditor": "auditor_category",
    # === Appointment Info ===
    "dropdownlist1": "appointment_type",
    "dateofappsect_d": "appointment_date",
    "dateannualgenmeet_d": "agm_date",
    "whrauditorapp": "auditor_appointed_in_agm",
    "dateofaccauditedfrom_d": "accounting_period_from",
    "dateofaccauditedto_d": "accounting_period_to",
    "numoffinanyearapp": "number_of_years_appointed",
    "whrtinlimit": "within_20_company_limit",
    "whtrcmpnyfallclassofcmpny": "is_class_company_139(2)",
    "whtrjointaudappoint": "joint_auditors",
    # === Signing Authority ===
    "resonum": "board_resolution_number",
    "dinofdir_c": "signing_director_din",
    "desigd_c": "signing_director_designation",
    # === 10-Year Appointment History ===
    "textfield6_1": "previous_appointment_start_1",
    "textfield7_1": "previous_appointment_end_1",
    "textfield6_2": "previous_appointment_start_2",
    "textfield7_2": "previous_appointment_end_2",
    "textfield6_3": "previous_appointment_start_3",
    "textfield7_3": "previous_appointment_end_3",
    "textfield6_4": "previous_appointment_start_4",
    "textfield7_4": "previous_appointment_end_4",
    "textfield6_5": "previous_appointment_start_5",
    "textfield7_5": "previous_appointment_end_5",
    "textfield6_6": "previous_appointment_start_6",
    "textfield7_6": "previous_appointment_end_6",
    "textfield6_7": "previous_appointment_start_7",
    "textfield7_7": "previous_appointment_end_7",
    "textfield6_8": "previous_appointment_start_8",
    "textfield7_8": "previous_appointment_end_8",
    "textfield6_9": "previous_appointment_start_9",
    "textfield7_9": "previous_appointment_end_9",
    "textfield6_10": "previous_appointment_start_10",
    "textfield7_10": "previous_appointment_end_10",
}
